[build]
  command = "astro build"
  publish = "dist"

[functions]
  directory = ".netlify/functions-internal"
  node_bundler = "esbuild"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"