[build]
  command = "astro build"
  publish = "dist"

[functions]
  directory = ".netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-functions-core"

[[plugins]]
  package = "@netlify/plugin-local-install-core"