[build]
  command = "astro build && cp -r public/locales .netlify/functions-internal/ssr/"
  publish = "dist"

[functions]
  directory = ".netlify/functions-internal"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"